import '@/styles/globals.css'

import { useState } from 'react'
import AppContext from '@/context/AppContext'
import Head from 'next/head'
import Layout from '@/components/Layout'
import songs from '@/context/songsJson'



export default function App({ Component, pageProps }) {

  const [coins,setCoins] = useState(5)
  const [songList,setSongList] = useState([])
  var songCardFlag = {}
  var setSongCardFlag = {}
  songs.map( song => {
    [songCardFlag[song._id],setSongCardFlag[song._id]] = useState(false)
  })

  return (
    <AppContext.Provider
    value={{
      state:{
        coins,
        songList,
        songCardFlag,
      },
      setCoins,
      setSongList,
      setSongCardFlag,
      songs
    }}
    
    >

      <Head>
        <title>Jukebox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout><Component {...pageProps} /></Layout>  

    </AppContext.Provider>
  )
}
